app:
  build: containers/api
  volumes:
    - /var/www
nginx:
  build: containers/nginx
  links:
    - php
  ports:
    - 80:80
    - 443:443
  volumes_from:
    - app
php:
  build: containers/php-fpm
  ports:
    - 9000:9000
  volumes_from:
    - app
