app:
  build: containers/api
  links:
    - db
  volumes:
    - ./containers/api/code:/var/www
  tty: true
nginx:
  build: containers/nginx
  links:
    - php
  ports:
    - 80:80
    - 443:443
  volumes_from:
    - app
php:
  build: containers/php-fpm
  links:
    - db
  ports:
    - 9000:9000
  volumes_from:
    - app
db:
  image: redis
