app:
  build: containers/symfony
  volumes:
    - ./containers/symfony/code:/var/www
  tty: true
nginx:
  build: containers/nginx
  links:
    - php
  ports:
    - 80:80
    - 443:443
  volumes_from:
    - app
php:
  build: containers/php-fpm
  ports:
    - 9000:9000
  volumes_from:
    - app    
