app:
  build: containers/api
  links:
    - db

nginx:
  build: containers/nginx
  ports:
    - 80:80
    - 443:443

php:
  build: containers/php-fpm
  links:
    - db
  ports:
    - 9000:9000
  volumes_from:
    - app

db:
  image: mongo
  ports:
    - 27017:27017
