nginx:
  build: docker/nginx
  links:
    - php
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./config/nginx/:/etc/nginx
    - ./log/nginx/:/var/log/nginx
    - ./data/nginx/:/home/http
php:
  build: docker/phpfpm
  ports:
    - "9000:9000"
