nginx:
  build: docker/nginx
  links:
    - phpfpm
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - config/nginx:/etc/nginx
    - log/nginx:/var/log/nginx
    - data/nginx:/home/http
phpfpm:
  build: docker/phpfpm
  links:
    - memcached
  ports:
    - "9000:9000"
  volumes:
    - data/php:/home/http
memcached:
  build: docker/memcached
  ports:
    - "11211:11211"
 
